apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: open5gs
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "open5gs"
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - "amf.open5gs.svc.cluster.local:9090"
              - "smf.open5gs.svc.cluster.local:9090"
              - "upf.open5gs.svc.cluster.local:9090"
                #- "nrf.open5gs.svc.cluster.local:9090"
                #- "udr.open5gs.svc.cluster.local:9090"
                #- "udm.open5gs.svc.cluster.local:9090"
              - "pcf.open5gs.svc.cluster.local:9090"
                #- "ausf.open5gs.svc.cluster.local:9090"
                #- "bsf.open5gs.svc.cluster.local:9090"
                #- "nssf.open5gs.svc.cluster.local:9090"
                #- "scp.open5gs.svc.cluster.local:9090"


